### ISSUE TITLE
Show number of results in addition to pages

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/can-link#16]
When I do a search (e.g., Russian) and get to the results screen, in addition to the indication of 'Page 1 of 8' it might be nice to see the total number of results.

![image](https://user-images.githubusercontent.com/4697932/90427705-24705a00-e080-11ea-8401-44622ca43cbb.png)

**Comment by johnhuck** [comment]
Agreed. Since number of results are shown when you hover over word bubbles and so on, it does seem odd that there is no display of total number of results.

**Comment by jchartrand** [comment]
I've changed it to show total results (just let me know if it should be shown differently):

<img width="604" alt="image" src="https://user-images.githubusercontent.com/547165/100553129-fcd18600-3259-11eb-822a-7e03d1e17e53.png">

**Comment by sfarnel** [comment]
Looks great! Closing issue.
