### ISSUE TITLE
Format of dropdown list for Creator

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/can-link#18]
The current list has 'pins' beside the individual's name or the subject which looks a bit weird when it isn't places that are being named. Can these be removed? (Or perhaps purpose clarified as maybe I'm just used to these for mapping interfaces)

![image](https://user-images.githubusercontent.com/4697932/90432930-47067100-e088-11ea-8f99-9dd1200a2ccf.png)

**Comment by johnhuck** [comment]
I also associate the pins with maps.

**Comment by sfarnel** [comment]
Looks great! Closing issue
