### ISSUE TITLE
Map view when searching from within results page

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/can-link#20]
(That issue name isn't very clear so I'll try and capture it better here). So, say I search from the home page (e.g. Russian) and then from the results page I start typing in the Creator box and then select a name and then hit search. The map view refreshes to look like this (which seems to be a very precise location on the UA campus?) Perhaps this needs some rethinking?

![image](https://user-images.githubusercontent.com/4697932/90434859-5affa200-e08b-11ea-8d51-b12044e13fb6.png)

**Comment by johnhuck** [comment]
The level of map zoom seems too close in many cases. I agree, it's a little distracting. I don't know what's under the hood, but could it be a question of using a spatial extent/footprint rather than a point for named places, I wonder.

**Comment by jchartrand** [comment]
@sfarnel @johnhuck 

I had added some handling that sets the map's bounds to something like 10% bigger than an area that would just show all the results (universities with matching theses), which pretty clearly doesn't work when there is a single university.  

I could set the zoom to just always show the whole of Canada, which might make most sense?

Note too that we should probably talk a bit about the size of the bubbles on the map, whose sizes don't directly match the result sizes -- I cap the size of the bubble at some limit after which the bubble just stays the same size (so a university with ten thousand results has the same size bubble as one with thirty thousand) and similarly on the low end - there is a minimum bubble size so a university with one result has the same sized bubble as a university with a hundred results.  Should I take that scaling off for now and everyone can see how it looks?

**Comment by sfarnel** [comment]
Thanks @jchartrand Why not try having the Zoom just sow the entire map of Canada (with perhaps just the bubble for the single university in question showing?). And let's try your approach with the size of bubbles on the map to see what it looks like with some extremes at both ends of the scale (1 result, thousands of results) to see how it looks

**Comment by jchartrand** [comment]
@sfarnel 

I've removed the maximum and minimums on the bubbles, and I've set the map to always show all of Canada.  you'll quickly see that universities with few results barely show even a dot.  Let me know if there should be maybe ranges of size, like say five different sizes of bubble - 1-100 results, 100-500, etc.

I don't have the bounds on the map quite right I don't think, but thought it better to just get it up as-is and get feedback.   You could move the map around and zoom it to get it how you'd like, then take a screenshot and post it here, and I can then set it to show that way.

I also spent a little time looking at how we could make the map a bit prettier, and I think I could do some things like highlight just Canada (kind of grading out the U.S.), and/or colouring the provinces.  Not sure if you'd like me to spend some time on that.  Might take a few hours.

For reference, here is what the map looked like before (for all results):

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/547165/101045803-8cbf4a80-354e-11eb-9eb0-fad685f2a2a0.png">

**Comment by sfarnel** [comment]
Thanks @jchartrand This is a tricky one to get right isn't it?! Strangely I think I like the way the all results map displays in the image above better than I like how it is now. I also noted that when I do a search now that gets not many results the map shows but seems to have nothing on it, I imagine because the bubbles are too small. For example, do a search for adventure writing which has 66 hits. The map looks like this:

![image](https://user-images.githubusercontent.com/4697932/101174583-54c50f80-3601-11eb-80a1-1b0e7c374beb.png)

Maybe go back to the old version but use a range of bubble sizes like you suggest, i.e., 1-100 results, 100-500, etc.

How does that sound?

**Comment by jchartrand** [comment]
@sfarnel

How does this look for the smallest bubble, which would be for schools with between 1 and 100 matching theses:

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/547165/101811046-8ea58280-3ae7-11eb-939e-6f1b6a094b9f.png">

**Comment by jchartrand** [comment]
@sfarnel

Also:  in that example above, you can see that the map remains zoomed to show the entirety of Canada.  When there are results for just a single school (like in the example) or a group of schools that are in the same area of Canada, should the map zoom in a bit more closely on that area?

**Comment by jchartrand** [comment]
@sfarnel 

And this is what the map looks like when showing all results:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/547165/101811354-fcea4500-3ae7-11eb-91e1-c23c1b929cee.png">

Should the biggest bubbles be bigger?  Or any other sizes changed?

**Comment by sfarnel** [comment]
Thanks @jchartrand I think this is really great! When there are results for just a single school or a group of schools that are in the same area of Canada, if the map could zoom in a bit more on that area, I think that would be great, but not a deal breaker if not.

**Comment by sfarnel** [comment]
Done. Closing issue
