### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jchartrand** [ualbertalib/can-link#52]
Update the README.

Explain how to change SOLR queries.

How to run in development mode.

How to deploy.

**Comment by danydvd** [comment]
@jchartrand Thanks this looks great. One thing that I am interested in is how you build the SOLR queries (before sending the XHR. I would really appreciate it if we can have a brief description (or maybe a pointer to the part of the script that is doing this).

**Comment by jchartrand** [comment]
@danydvd Yes, no problem.  I’ll write it up and also talk it over with you.  It is fairly straightforward.  I just take the form inputs, construct the solr query string, and send it off.

**Comment by jchartrand** [comment]
@danydvd I’ve updated the README.  Let me know if it seems clear enough - happy to elaborate as needed.  And let me know if you want a talk/walk through.

**Comment by danydvd** [comment]
@jchartrand this looks great thank you so much.

**Comment by jchartrand** [comment]
@danydvd You are very welcome.

**Comment by sfarnel** [comment]
Done. Closing
