### ISSUE TITLE
Add link to fulltext of thesis on brief results

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/can-link#55]
Add the link (e.g. doi) to the thesis be shown in the record popup (see below). Right now the user has to go to the full record in order to retrieve it.

![image](https://user-images.githubusercontent.com/4697932/98589273-41d15080-228a-11eb-9444-a7171658ef12.png)

**Comment by johnhuck** [comment]
See my comments on https://github.com/ualbertalib/can-link/issues/53 about the idea of either showing the full set of fields on the pop up or cutting out the pop up. Not sure how those suggestions dovetail with the issue. In any event, we are in agreement that the information on the pop up now is not enough.

**Comment by sfarnel** [comment]
Looks great! Closing issue
