### ISSUE TITLE
Create page for individual subjects

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/can-link#56]
Create a separate page for individual subjects?(e.g. http://206.167.181.124:8000/getitem/http://canlink.library.ualberta.ca/subject/e52aafb06de949864871fd8885da9b04)

**Comment by jchartrand** [comment]
@sfarnel 

Does this mean create a new HTML page in can-link that maybe more nicely formats and displays the subject info that comes out of the triple store?

Or would we put the some specific set of subject related data into SOLR and I'd create a page to show that  data?

**Comment by sfarnel** [comment]
Thanks @jchartrand I think what we have in mind here (@danydvd chime in also!) is the first option, i.e., a page that shows the info for the subject as well as items that have that subject.

**Comment by danydvd** [comment]
Thanks @jchartrand. I agree @sfarnel that first option is what I was thinking too. For this we can use the subject_url (in SOLR) and query the triple to get all fields in the subject.

**Comment by jchartrand** [comment]
@danydvd I guess this is actually pretty similar to #57 at least in so far as we'd probably use the same SPARQL query?

So, like with #57, how would I run a SPARQL query from the web browser - is there a RESTful endpoint?

**Comment by jchartrand** [comment]
@danydvd As with #57 - can you enable CORS on the sparql endpoint?  I need to pull the RDF in using XHR (therefore need the CORS) and then render the RDF nicely.

**Comment by jchartrand** [comment]
@sfarnel @danydvd 

The new subject page will be linked from the subjects listed on the thesis record page? 

 i.e., from:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/547165/102790681-d04ded00-4373-11eb-9c63-b189789af89d.png">

**Comment by sfarnel** [comment]
Thanks @jchartrand yes, I think this makes the most sense. What do you think @danydvd

**Comment by danydvd** [comment]
@jchartrand I agree. Each subject in the subjects list would be link to its own page.

**Comment by jchartrand** [comment]
@sfarnel @danydvd 

I've created the Subject page, but I've discovered that there isn't really anything to show from the returned RDF, other than the label.  The other triples wouldn't (I don't think) mean much to people, but maybe I'm wrong.

So, I just show whatever RDF is available, with a 'select' dropdown with which to choose the serialization.

I'm not sure what I could show other than the RDF.  I guess I could possibly render the triples in something like a three column grid (subject, predicate, object), but that probably wouldn't look much different than turtle/n3.

**Comment by sfarnel** [comment]
Thanks @jchartrand A couple thoughts; @danydvd chime in as well:

I think we were also wondering about showing the identifiers for all items that have that subject
It might be nice to have a more user friendly format for display; maybe we can add this after the fact

**Comment by sfarnel** [comment]
Complete. Closing issue
